services:
  eliza:
    image: ghcr.io/706creators/eliza-app:20250201
    container_name: eliza
    stdin_open: true
    tty: true
    environment:
      - REDPILL_API_KEY=${REDPILL_API_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 8G
        reservations:
          cpus: "1"
          memory: 4G
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    restart: always
    
  nginx:
    image: phalanetwork/docker-log-api
    container_name: logs
    ports:
      - "8080:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 256M
        reservations:
          cpus: "0.05"
          memory: 128M
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    restart: unless-stopped
    depends_on:
      - mkswap
  mkswap:
    image: busybox
    privileged: true
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        if ! [ -f /host/swap0 ]; then 
          fallocate -l 4G /host/swap0 && 
          chmod 600 /host/swap0 && 
          mkswap /host/swap0 && 
          swapon /host/swap0
        fi
        echo 30 > /host/proc/sys/vm/swappiness
    volumes:
      - /:/host
    restart: "no"
