services:
  eliza:
    image: ghcr.io/706creators/eliza-app:20250203
    container_name: eliza
    environment:
      - ATOMASDK_BEARER_AUTH=${ATOMASDK_BEARER_AUTH}
      - REDPILL_API_KEY=${REDPIIL_API_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - SUI_PRIVATE_KEY=${SUI_PRIVATE_KEY}
      - SUI_NETWORK=${SUI_NETWORK}
      - DEFAULT_LOG_LEVEL=info
    ports:
      - "3000:3000"
      - "5173:5173"
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 8G
        reservations:
          cpus: "1"
          memory: 4G
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    restart: always
