name: Deploy to GitHub Pages

on:
  # 手动触发部署
  workflow_dispatch:

  push:
    branches:
      - main
      

# 添加权限配置
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 9.4.0

      - uses: actions/setup-node@v4
        with:
          node-version: "23"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run build
        run: pnpm run build
      
      - name: Add cname 
        run: echo "eliza101.xyz" > ./packages/page/dist//CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/page/dist/
          # 保持提交历史
          force_orphan: false
          commit_message: 'deploy: ${{ github.event.head_commit.message }}' 